#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path('../lib', __dir__)

require 'calibration_frequency_changes'

$stdout.sync = true
$stderr.sync = true

puts CalibrationFrequencyChanges.new(ARGV.first).repeated_frequency
